source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

source/quote_app/urls.py
from django.urls import include, path
from rest_framework import routers
from quote_app import views
from quote_app.views.index import index

router = routers.DefaultRouter()
router.register(r'quotes', views.QuoteViewSet)

app_name = 'quote_app'

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('index/', index, name='index'),
]

source/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api_v2/', include('quote_app.urls')),
]

source/accounts/models.py
from django.db import models

# Create your models here.

source/quote_app/models.py
from django.db import models

status_choices = [('new', 'новая'), ('moderated', 'модерированная')]


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


    # Create your models here.
    # текст - текстовое поле;
    # имя добавившего - строка;
    # email добавившего - поле для email-а;
    # рейтинг - целое число, по умолчанию 0;
    # статус - новая или модерированная, по умолчанию - новая;
    # дата и время добавления - автозаполнение.

class Quote(BaseModel):
    text = models.TextField(max_length=500, null=False, blank=False, verbose_name='Текст')
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Имя добавившего')
    email = models.EmailField(max_length=100, null=False, blank=False, verbose_name='емаил')
    rating = models.IntegerField(null=True, blank=True, default=0,  verbose_name='рейтинг')
    status = models.CharField(max_length=50, null=False,
                              blank=False,
                              choices=status_choices,
                              default='new', verbose_name='статус')

    class Meta:
        permissions = [('list_quotes', 'list quotes')]

    def __str__(self):
        return "Имя {}. Рейтинг {} . Статус {}".format(self.name, self.rating, self.status)


# class Rating(BaseModel):
#     quote = models.ForeignKey('quote_app.Quote', on_delete=models.CASCADE, related_name='rating')
#     rating = models.

source/accounts/views.py
from django.shortcuts import render

# Create your views here.

source/quote_app/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

source/quote_app/views/quotes.py
from rest_framework import viewsets
from quote_app.models import Quote
from quote_app.permissions import QuotePermission
from quote_app.serializers.quote_serializer_get import QuoteSerializerGet
from quote_app.serializers.quote_serializer_post import QuoteSerializerPost


class QuoteViewSet(viewsets.ModelViewSet):
    queryset = Quote.objects.all()
    serializer_class = QuoteSerializerGet
    permission_classes = [QuotePermission]

    def get_serializer_class(self):
        if self.request.method == "POST":
            return QuoteSerializerPost
        elif self.request.method == "GET":
            return QuoteSerializerGet

    def get_queryset(self):
        queryset = super().get_queryset()
        print(queryset)
        if self.request.user.is_authenticated and self.request.user.has_perm('quote_app.list_quotes'):
            return queryset
        else:
            return queryset.filter(status='moderated')

source/quote_app/views/rating.py
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views import View

from quote_app.models import Quote


class IncreaseRating(View):

    def get(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote, pk=self.kwargs.get('pk'))
        user = request.user
        quote.rating +=1
        quote.save()


class DecreaseRating(View):
    def get(self, request, *args, **kwargs):
        quote = get_object_or_404(Quote, pk=self.kwargs.get('pk'))
        user = request.user
        quote.rating -= 1
        quote.save()

source/quote_app/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Tasks{% endblock %}</title>
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/v5.11.1/css/free.min.css" media="all">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <nav style="position: static" class="navbar">

    <div class="container">
    <ul class="menu">
        <li><button id="main" onclick="indexQuotes(event)">Главная</button></li>
        {% block menu %}
        {% endblock %}

            {% if user.is_authenticated %}
                {% block menu_links %}{% endblock %}
                    <li class="menu-right"><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}" class="nav-link">Выход</a></li>
                    <li class="menu-right">Привет, {{ user.username }}!</li>
                {% else %}
                    <li class="menu-right"><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}" class="nav-link">Вход</a></li>
            {% endif %}

    </ul>
    </div>
    </nav>

    <div class="container">

текст - текстовое поле;
имя добавившего - строка;
email добавившего - поле для email-а;
рейтинг - целое число, по умолчанию 0;
статус - новая или модерированная, по умолчанию - новая;
дата



        <input type=button value="Quote" name="quotes" data-url="#">
        <input type=button value="Add Quote" name="quotes" id='add' data-url="#">

        <div id="quote" > Цитаты </div>

        <form id="form" style="display: none">
            Text : <input type="text" id="text"><br>
            Имя добавившего : <input type="text" id="author"><br>
            Email: <input type="text" id="email"><br>
            <button id="send">send</button>
        </form>
        {% block content %}

        {% endblock %}
    </div>


    <script src="{% static 'js/javascript.js' %}">

    </script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>